---
version: "3.7"
services:
  redis:
    image: redis:6-alpine
    entrypoint: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis:/data:delegated
volumes:
  redis:
